import { useEffect, useState } from 'react';
import { Card, Button } from '@/components/ui';
import type { MomFiltersInput, MomNextStepItem } from '@/hooks/useMomReport';
import { useMomSection, useSaveMomNextSteps } from '@/hooks/useMomReport';

const GROUP_LABEL: Record<string, string> = {
  mes: 'This month',
  ads: 'Ads',
  countries: 'Countries',
  email: 'Email',
  cro: 'CRO',
};

interface S0Payload {
  status: string;
  month: string;
  items: MomNextStepItem[];
  autoGenerated: boolean;
  groups: string[];
}

/**
 * M4 (monthly-report-v2-mom.md §M4) — S0 "Next Steps carryover... Editable
 * checklist UI; More/Better/New template buttons (slide 29)." The list the
 * backend returns is already the M-1 carry-forward when nothing's been saved
 * yet (SNextStepsSection::build()) — this component's job is purely the
 * editable checklist + save, full-replace on every save (same contract as
 * the customizer's layout save).
 */
export function SNextStepsCard({ slug, filters, label }: { slug: string; filters: MomFiltersInput; label: string }) {
  const { data, isLoading } = useMomSection<S0Payload>(slug, 'S0', filters, true);
  const save = useSaveMomNextSteps(slug);
  const [items, setItems] = useState<MomNextStepItem[]>([]);
  const [dirty, setDirty] = useState(false);

  useEffect(() => {
    if (data?.items) {
      setItems(data.items);
      setDirty(false);
    }
  }, [data]);

  if (isLoading) {
    return (
      <Card style={{ padding: 18 }}>
        <div style={{ fontSize: 14, fontWeight: 650, marginBottom: 8 }}>{label}</div>
        <div className="muted text-sm">Loading…</div>
      </Card>
    );
  }

  const month = data?.month ?? filters.month;
  const groups = data?.groups ?? Object.keys(GROUP_LABEL);

  const addItem = (group: string) => {
    setItems((s) => [...s, { text: '', group: group as MomNextStepItem['group'], status: 'open', carriedFrom: null }]);
    setDirty(true);
  };
  const updateItem = (i: number, patch: Partial<MomNextStepItem>) => {
    setItems((s) => s.map((it, idx) => (idx === i ? { ...it, ...patch } : it)));
    setDirty(true);
  };
  const removeItem = (i: number) => {
    setItems((s) => s.filter((_, idx) => idx !== i));
    setDirty(true);
  };

  const onSave = () => {
    if (!month) return;
    save.mutate(
      { month, items: items.filter((it) => it.text.trim() !== '') },
      { onSuccess: () => setDirty(false) },
    );
  };

  return (
    <Card style={{ padding: 18 }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 }}>
        <div style={{ fontSize: 14, fontWeight: 650 }}>{label}</div>
        {data?.autoGenerated && <span className="muted text-sm">Pre-filled from last month · not yet saved</span>}
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 6, marginTop: 8 }}>
        {items.length === 0 && <div className="muted text-sm">No open items — add one below.</div>}
        {items.map((it, i) => (
          <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <select
              className="input"
              style={{ width: 90, fontSize: 11 }}
              value={it.status}
              onChange={(e) => updateItem(i, { status: e.target.value as MomNextStepItem['status'] })}
            >
              <option value="open">Open</option>
              <option value="done">Done</option>
              <option value="dropped">Dropped</option>
            </select>
            <select
              className="input"
              style={{ width: 110, fontSize: 11 }}
              value={it.group}
              onChange={(e) => updateItem(i, { group: e.target.value as MomNextStepItem['group'] })}
            >
              {groups.map((g) => (
                <option key={g} value={g}>
                  {GROUP_LABEL[g] ?? g}
                </option>
              ))}
            </select>
            <input
              className="input"
              style={{ flex: 1, textDecoration: it.status === 'dropped' ? 'line-through' : undefined }}
              value={it.text}
              placeholder="What needs to happen…"
              onChange={(e) => updateItem(i, { text: e.target.value })}
            />
            {it.carriedFrom && (
              <span className="muted" style={{ fontSize: 10, whiteSpace: 'nowrap' }} title={`Carried from ${it.carriedFrom}`}>
                ↩ {it.carriedFrom}
              </span>
            )}
            <Button size="sm" variant="ghost" type="button" onClick={() => removeItem(i)}>
              ✕
            </Button>
          </div>
        ))}
      </div>

      <div style={{ display: 'flex', gap: 8, marginTop: 10 }}>
        {groups.map((g) => (
          <Button key={g} size="sm" variant="ghost" type="button" onClick={() => addItem(g)}>
            + {GROUP_LABEL[g] ?? g}
          </Button>
        ))}
        <span style={{ flex: 1 }} />
        <Button size="sm" variant="secondary" type="button" disabled={!dirty || save.isPending || !month} onClick={onSave}>
          {save.isPending ? 'Saving…' : 'Save checklist'}
        </Button>
      </div>
    </Card>
  );
}
