<?php

declare(strict_types=1);

namespace App\Reports\Mom\Sections;

use App\Models\Brand;
use App\Models\ReportNextStep;
use App\Reports\Contracts\ReportFilters;
use App\Reports\Mom\Contracts\MomSection;
use Carbon\CarbonImmutable;

/**
 * M4 (monthly-report-v2-mom.md §M4) — "S0 Next Steps carryover (slide 3 +
 * 28-29)... Generating month M pre-fills from M-1's open items (the PDF's
 * 'copiar y pegar para ver status' — automated). Editable checklist UI;
 * More/Better/New template buttons (slide 29)."
 *
 * build() is READ-ONLY: when no report_next_steps row exists yet for month M,
 * it COMPUTES the carry-forward from M-1's open items and returns it with
 * `autoGenerated: true` — nothing is persisted until the agency actually
 * saves the checklist via `PUT brands/{brand}/reports/mom/next-steps`
 * (MomSectionController::saveNextSteps). A GET must never have a write side
 * effect; the pre-fill is recomputed fresh every time until someone edits it.
 *
 * "More/Better/New template buttons" (slide 29) are a pure client-side
 * affordance (they just append a blank item pre-tagged with a group) — not
 * built here, this section only owns the data contract they write into.
 */
final class SNextStepsSection implements MomSection
{
    /** @var array<int, string> */
    private const GROUPS = ['mes', 'ads', 'countries', 'email', 'cro'];

    public function key(): string
    {
        return 'S0';
    }

    public function build(Brand $brand, ReportFilters $filters): array
    {
        $tz = $brand->timezone ?: 'UTC';
        $month = $filters->month ?? CarbonImmutable::now($tz)->subMonth()->format('Y-m');

        $row = ReportNextStep::query()
            ->where('brand_id', $brand->id)
            ->where('month', $month)
            ->first();

        if ($row !== null) {
            $stored = is_array($row->items) ? $row->items : [];

            return [
                'key'           => $this->key(),
                'status'        => 'ok',
                'month'         => $month,
                // Normalised to the SAME shape as the auto-generated branch
                // below (camelCase `carriedFrom`) — saveNextSteps() persists
                // `carried_from` (matching the spec's own field name), but the
                // API response must be one consistent shape regardless of
                // whether these items came from a saved row or a fresh
                // carry-forward computation.
                'items'         => array_map(static fn (array $i): array => [
                    'text'        => (string) ($i['text'] ?? ''),
                    'group'       => in_array($i['group'] ?? null, self::GROUPS, true) ? $i['group'] : 'mes',
                    'status'      => in_array($i['status'] ?? null, ['open', 'done', 'dropped'], true) ? $i['status'] : 'open',
                    'carriedFrom' => $i['carriedFrom'] ?? $i['carried_from'] ?? null,
                ], $stored),
                'autoGenerated' => false,
                'groups'        => self::GROUPS,
            ];
        }

        $prevMonth = CarbonImmutable::parse($month . '-01', $tz)->subMonth()->format('Y-m');
        $prevRow = ReportNextStep::query()
            ->where('brand_id', $brand->id)
            ->where('month', $prevMonth)
            ->first();

        $carried = [];
        if ($prevRow !== null && is_array($prevRow->items)) {
            foreach ($prevRow->items as $item) {
                if (($item['status'] ?? null) !== 'open') {
                    continue; // only OPEN items carry forward — done/dropped stay in M-1's history.
                }
                $carried[] = [
                    'text'        => (string) ($item['text'] ?? ''),
                    'group'       => in_array($item['group'] ?? null, self::GROUPS, true) ? $item['group'] : 'mes',
                    'status'      => 'open',
                    'carriedFrom' => $prevMonth,
                ];
            }
        }

        return [
            'key'           => $this->key(),
            'status'        => 'ok',
            'month'         => $month,
            'items'         => $carried,
            // true whenever this month has never been saved yet — even an
            // empty carry-forward (no prior open items / no M-1 row at all)
            // still means "nothing saved for M yet", so the SPA knows to show
            // this as a draft rather than a confirmed, saved checklist.
            'autoGenerated' => true,
            'groups'        => self::GROUPS,
        ];
    }
}
