<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Models\Brand;
use App\Models\ReportNextStep;
use App\Models\ReportNote;
use App\Models\User;
use Carbon\CarbonImmutable;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

/**
 * M4 (monthly-report-v2-mom.md §M4) — the editorial layer: S0 (Next Steps
 * carryover, read-only pre-fill from M-1's open items until saved) and S19
 * (Novedades, brand-copy -> agency-default resolution).
 */
class MomM4Test extends TestCase
{
    use RefreshDatabase;

    private const TZ = 'Europe/Madrid';

    private function makeBrand(): Brand
    {
        return Brand::factory()->create(['base_currency' => 'EUR', 'timezone' => self::TZ, 'status' => 'active']);
    }

    private function actingMasterAdmin(): User
    {
        $user = User::factory()->create(['role' => 'master_admin']);
        Sanctum::actingAs($user);

        return $user;
    }

    public function test_shell_reports_s0_and_s19_ready(): void
    {
        $this->actingMasterAdmin();
        $brand = $this->makeBrand();

        $sections = collect($this->getJson("/api/brands/{$brand->slug}/reports/mom")->assertOk()->json('sections'))->keyBy('key');
        $this->assertTrue($sections['S0']['ready']);
        $this->assertTrue($sections['S19']['ready']);
    }

    public function test_s0_prefills_open_items_from_previous_month_without_persisting(): void
    {
        $this->actingMasterAdmin();
        $brand = $this->makeBrand();

        ReportNextStep::query()->create([
            'brand_id' => $brand->id,
            'month'    => '2026-06',
            'items'    => [
                ['text' => 'Fix Google feed',    'group' => 'ads',   'status' => 'open',   'carried_from' => null],
                ['text' => 'Already shipped fix', 'group' => 'mes',  'status' => 'done',   'carried_from' => null],
                ['text' => 'Abandoned idea',      'group' => 'cro',  'status' => 'dropped', 'carried_from' => null],
            ],
        ]);

        $res = $this->getJson("/api/brands/{$brand->slug}/reports/mom/sections/S0?month=2026-07")
            ->assertOk()->assertJsonPath('status', 'ok');

        $this->assertTrue($res->json('autoGenerated'));
        $items = $res->json('items');
        $this->assertCount(1, $items);
        $this->assertSame('Fix Google feed', $items[0]['text']);
        $this->assertSame('2026-06', $items[0]['carriedFrom']);

        // A GET never writes — no row for 2026-07 should exist yet.
        $this->assertDatabaseMissing('report_next_steps', ['brand_id' => $brand->id, 'month' => '2026-07']);
    }

    public function test_s0_save_then_read_returns_saved_items_not_autogenerated(): void
    {
        $this->actingMasterAdmin();
        $brand = $this->makeBrand();

        $payload = [
            'month' => '2026-07',
            'items' => [
                ['text' => 'New test item', 'group' => 'countries', 'status' => 'open', 'carriedFrom' => null],
            ],
        ];
        $this->putJson("/api/brands/{$brand->slug}/reports/mom/next-steps", $payload)->assertOk()->assertJsonPath('ok', true);

        $res = $this->getJson("/api/brands/{$brand->slug}/reports/mom/sections/S0?month=2026-07")->assertOk();
        $this->assertFalse($res->json('autoGenerated'));
        $this->assertCount(1, $res->json('items'));
        $this->assertSame('New test item', $res->json('items.0.text'));
    }

    public function test_s19_resolves_brand_copy_over_agency_default_and_reports_absence_honestly(): void
    {
        $this->actingMasterAdmin();
        $brand = $this->makeBrand();

        // No notes at all yet -> honest no_data, never an empty-but-present block.
        $this->getJson("/api/brands/{$brand->slug}/reports/mom/sections/S19?month=2026-07")
            ->assertOk()->assertJsonPath('status', 'no_data');

        ReportNote::query()->create(['brand_id' => null, 'month' => '2026-07', 'body' => 'Agency-wide talking point.']);
        $resWorkspace = $this->getJson("/api/brands/{$brand->slug}/reports/mom/sections/S19?month=2026-07")->assertOk();
        $this->assertSame('workspace', $resWorkspace->json('source'));
        $this->assertFalse($resWorkspace->json('isBrandOverride'));

        $this->putJson("/api/brands/{$brand->slug}/reports/mom/novedades", ['month' => '2026-07', 'body' => 'Brand-specific copy.'])
            ->assertOk()->assertJsonPath('ok', true);

        $resBrand = $this->getJson("/api/brands/{$brand->slug}/reports/mom/sections/S19?month=2026-07")->assertOk();
        $this->assertSame('brand', $resBrand->json('source'));
        $this->assertTrue($resBrand->json('isBrandOverride'));
        $this->assertSame('Brand-specific copy.', $resBrand->json('body'));
    }

    public function test_workspace_novedades_default_requires_master_admin(): void
    {
        $manager = User::factory()->create(['role' => 'manager']);
        Sanctum::actingAs($manager);

        $this->putJson('/api/workspace-novedades', ['month' => '2026-07', 'body' => 'x'])->assertForbidden();

        Sanctum::actingAs(User::factory()->create(['role' => 'master_admin']));
        $this->putJson('/api/workspace-novedades', ['month' => '2026-07', 'body' => 'Agency default text.'])
            ->assertOk()->assertJsonPath('ok', true);
        $this->getJson('/api/workspace-novedades?month=2026-07')->assertOk()->assertJsonPath('body', 'Agency default text.');
    }
}
